[package]
name = "monkey-lang-rs"
version = "0.1.0"
edition = "2021"
default-run = "monkey"

[lib]
name = "monkey"
path = "src/lib.rs"

[[bin]]
name = "monkey"
path = "src/main.rs"

[[bin]]
name = "bench"
path = "src/bench.rs"

[dependencies]
